### ISSUE TITLE
Fsys Block Not Patched! - Serial Lenght Incorrect 

### ISSUE THREAD

**Issue by warnerbryce** [sadponyguerillaboy/Python-Apple-EFI-Patcher#1]
Hello,

I can't use the -s argument in your script. 

If i don't use it, the script works but i got this Warning at the end : Fsys Block Not Patched! - Serial Lenght Incorrect 
If i use the -s string and i put a valid 12 characters serial i got this error : 
`Traceback (most recent call last):  
  File "patcher.py", line 308, in <module>
    main(sys.argv[1:])
  File "patcher.py", line 217, in main
    final_patched_crc = binascii.unhexlify(fixed_patched_calc_crc32)
binascii.Error: Odd-length string
`

I use Python 3 on Ubuntu 18.04, it tried to use my serial under quotes, but it didn't get better.

Thank you for your answer.

**Comment by warnerbryce** [comment]
My bad, the ROM i used was bad, so your script didn't work well.
With another bin it's okay.

**Comment by sadponyguerillaboy** [comment]
will look into it now.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by warnerbryce** [comment]
Please don’t ! 
I use your script on another dump and it worked well. 

Envoyé de mon iPhone
